name: weread sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pydantic==1.10.18
          pip install git+https://github.com/jamalex/notion-py.git@refs/pull/671/merge
      - name: weread sync
        run: |
          python weread.py "${{secrets.WEREAD_COOKIE}}" "${{secrets.NOTION_TOKEN}}" "${{secrets.NOTION_DATABASE_ID}}" 
